# Generated by Django 4.1.3 on 2022-12-08 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('csv_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='dashboardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField()),
                ('dash_type', models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], help_text='Specify whether the dashboard is a draft or ready to be published', max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chartModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField()),
                ('chart_type', models.CharField(max_length=50)),
                ('assoc_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datamodel')),
                ('dash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dashboardmodel')),
            ],
        ),
    ]
