# Generated by Django 4.1.3 on 2022-12-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='user_id',
            new_name='data_user_id',
        ),
    ]
