# Generated by Django 4.1.3 on 2022-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datamodel_dashboardmodel_chartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='dash_type',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', help_text='Specify whether the dashboard is a draft or ready to be published', max_length=2),
        ),
    ]
