# Generated by Django 4.1.3 on 2022-12-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dashboardmodel_id_alter_datamodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='name',
            field=models.CharField(default='cherry', max_length=100),
            preserve_default=False,
        ),
    ]
