# Generated by Django 4.1.3 on 2022-12-26 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dashboardmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
